// <auto-generated />
using System;
using LightPi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightPi.Data.Migrations
{
    [DbContext(typeof(LightsContext))]
    partial class LightConfigurationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightPi.Shared.LightConfiguration", b =>
                {
                    b.Property<int>("LightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LightID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCCT")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDimmable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRGB")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxBrightness")
                        .HasColumnType("int");

                    b.Property<int?>("MaxColorTemp")
                        .HasColumnType("int");

                    b.Property<int?>("MinBrightness")
                        .HasColumnType("int");

                    b.Property<int?>("MinColorTemp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LightID");

                    b.ToTable("Lights");
                });
#pragma warning restore 612, 618
        }
    }
}
